# named list of all robots
fileversion: 3

robots:
  blue_1:
      enabled: true
      uri: udp://0.0.0.0:19850
      initial_position: [0.0, 0.0, 0.0]
      type: cf_blue_sim

  blue_2:
    enabled: true
    uri: udp://0.0.0.0:19851
    initial_position: [1.0, 0.0, 0.0]
    type: cf_blue_sim

  red_1:
    enabled: true
    uri: udp://0.0.0.0:19852
    initial_position: [1.0, 0.0, 0.0]
    type: cf_red_sim
  
  red_2:
    enabled: true
    uri: udp://0.0.0.0:19853
    initial_position: [1.0, 0.0, 0.0]
    type: cf_red_sim

# Definition of the various robot types
robot_types:
  cf_blue_sim:
    motion_capture:
      tracking: "vendor"
    big_quad: false
    firmware_logging:
      enabled: true
      default_topics:
        odom:
          frequency: 100
      custom_topics:
        body_rates:
          frequency: 100
          vars: ["stateEstimateZ.rateRoll", "stateEstimateZ.ratePitch", "stateEstimateZ.rateYaw"]
    firmware_params:
      ring:
        effect: 7 # 6: double spinner, 7: solid color, 16: packetRate
        solidBlue: 255 # if set to solid color
        solidGreen: 0 # if set to solid color
        solidRed: 0 # if set to solid color
        headlightEnable: 0

  cf_red_sim:
    motion_capture:
      tracking: "vendor"
    big_quad: false
    firmware_logging:
      enabled: true
      default_topics:
        odom:
          frequency: 100
      custom_topics:
        body_rates:
          frequency: 100
          vars: ["stateEstimateZ.rateRoll", "stateEstimateZ.ratePitch", "stateEstimateZ.rateYaw"]
    firmware_params:
      ring:
        effect: 7 # 6: double spinner, 7: solid color, 16: packetRate
        solidBlue: 0 # if set to solid color
        solidGreen: 0 # if set to solid color
        solidRed: 255 # if set to solid color
        headlightEnable: 0
        # pose:
        #   frequency: 100
      # angular_velocity:
      #   velocity:
      #     frequency: 100
      #     vars: ["stateEstimateZ.rollRate", "stateEstimateZ.pitchRate", "stateEstimateZ.yawRate"]

  cf21:
    motion_capture:
      tracking: "librigidbodytracker" # one of "vendor", "librigidbodytracker"
      # only if enabled; see motion_capture.yaml
      marker: default_single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    #firmware_logging:
    #   enabled: true
    #   default_topics:
    #   pose:
    #     frequency: 1 # Hz
    #   custom_topics:
    #    topic_name3: 
    #      frequency: 1
    #      vars: ["acc.x", "acc.y", "acc.z"]
    # reference_frame: "odom" 

  cf21_mocap_deck:
    motion_capture:
      tracking: "librigidbodytracker" # one of "vendor", "librigidbodytracker"
      # only if enabled; see motion_capture.yaml
      marker: mocap_deck
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    #firmware_logging:
    #   enabled: true
    #   default_topics:
    #   pose:
    #     frequency: 1 # Hz
    #   custom_topics:
    #    topic_name3: 
    #      frequency: 1
    #      vars: ["acc.x", "acc.y", "acc.z"]
    # reference_frame: "mocap" 

# global settings for all robots
all:
  # firmware logging for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_logging:
    enabled: true
    # default_topics:
     # remove to disable default topic
      # pose:
      #   frequency: 10 # Hz
      # status:
      #   frequency: 1 # Hz
    #custom_topics:
    #  topic_name1:
    #    frequency: 10 # Hz
    #    vars: ["stateEstimateZ.x", "stateEstimateZ.y", "stateEstimateZ.z", "pm.vbat"]
    #  topic_name2:
    #    frequency: 1 # Hz
    #    vars: ["stabilizer.roll", "stabilizer.pitch", "stabilizer.yaw"]
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 2 # 1: PID, 2: mellinger
    flightmode:
      stabModeRoll: 1
      stabModePitch: 1
      stabModeYaw: 0
    # ring:
    #   effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    # kalman:
    #   resetEstimation: 1
  # reference frame for on-board state-estimate of all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  reference_frame: "world"
  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats
